### ISSUE TITLE
Agregar funcionalidad de barra de estado al reproducir audio en pantalla extendida

### ISSUE THREAD

**Issue by lordzzz777** [lordzzz777/DrgonBollWiki#90]

**Comment by Jmejia-24** [comment]
[PR donde se realizo la corrección](https://github.com/lordzzz777/Dragon-Ball-Wiki/pull/93)

**Comment by Jmejia-24** [comment]
[Esta feature se trabajo en este PR](https://github.com/lordzzz777/Dragon-Ball-Wiki/pull/96)
